import { env } from '@/utils/env'

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export const logger = (object: unknown, comment?: string) => {
    if (!env.NEXT_PUBLIC_LOGGER) return

    // eslint-disable-next-line no-console
    console.log(
        '%c ============== INFO LOG \n',
        'color: #22D3EE',
        `${typeof window !== 'undefined' && window?.location.pathname}\n`,
        `=== ${comment ?? ''}\n`,
        object
    )
}
